# Generated by Django 3.1.3 on 2020-11-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestComment',
            new_name='Comment',
        ),
    ]
