# Generated by Django 3.1.3 on 2020-11-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20201125_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/munokitchen/image/upload/v1606644051/default_image_txvds7.png', upload_to='profile_pics'),
        ),
    ]
