# Generated by Django 3.1.3 on 2020-12-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20201129_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
    ]
