# Generated by Django 3.1.3 on 2020-12-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_suggetions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='part_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
