# Generated by Django 3.1.3 on 2020-12-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_tutorial_part_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorialseries',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorialseries',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
