# Generated by Django 3.1.3 on 2020-12-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20201203_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialseries',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
