# Generated by Django 3.1.3 on 2020-12-03 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_tutorialseries_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialseries',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
