# Generated by Django 3.1.3 on 2020-12-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20201203_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.ManyToManyField(to='mysite.Topic'),
        ),
        migrations.AddField(
            model_name='tutorialseries',
            name='topic',
            field=models.ManyToManyField(to='mysite.Topic'),
        ),
    ]
