# Generated by Django 3.1.3 on 2020-12-07 09:17

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
