# Generated by Django 3.1.3 on 2020-12-07 09:27

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_test_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
