# Generated by Django 3.1.3 on 2020-12-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20201207_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='content',
        ),
    ]
