# Generated by Django 3.1.3 on 2020-12-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20201209_1903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notification_Manual',
        ),
    ]
