# Generated by Django 3.1.3 on 2020-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_newsletter_user_agreements'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
