# Generated by Django 3.1.3 on 2020-12-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_tutorial_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.URLField(max_length=2083)),
                ('instagram', models.URLField(max_length=2083)),
                ('github', models.URLField(max_length=2083)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
