from django.urls import path
from .views import (
	TutorialList,
	register,
	HomePage,
	TutorialDetailView,
	BlogPostView,
	profile,
	BlogPostList,
	SearchResultsView,
	CommentDeleteView,
    About_page,
    SuggestionFormView,
    ConnectPage,
    CategoriesView,
    CategoryView,
    error404,
    error500,
    Notify_View,
)

urlpatterns = [
    path('',HomePage.as_view(),name='home'),
    path('about/',About_page.as_view(),name='about-page'),
    path('admin/notification/',Notify_View.as_view(),name='notify'),
    # path('error404/',error404,name='error404'),
    # path('error500/',error500,name='error500'),
    # path('notify/',Notifications_View.as_view(),name='notify'),
    path('categories/',CategoriesView.as_view(),name='categories'),
    path('categories/<slug:category>/',CategoryView.as_view(),name='category'),
    path('where-to-find-us/',ConnectPage.as_view(),name='connect'),
    path('suggestions/',SuggestionFormView.as_view(),name='suggetions'),
    # path('comment/delete/<int:id>',comment_delete,name='comment_delete'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='post-delete'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('blog/',BlogPostList.as_view(),name='blogs'),
    # path('tutorial/<series_name>/',HomeTutorialDetailView.as_view(),name='home_tutorial_detail'),
    path('tutorial/<series_name>/<tutorial>',TutorialDetailView.as_view(),name='tutorial_detail'),
    path('account/',profile,name='account'),
    path('tutorials/',TutorialList.as_view(),name='tutorials'),
    path('blog/<blogpost>/',BlogPostView.as_view(),name='blogpost'),

    # path('login/',LoginPage.as_view(),name='login'),
    # path('register/',RegisterPage.as_view(),name='register'),
    path('register/',register,name='register'),
]